name: AvertoxQuestSystem
version: 1.0.0
main: com.avertox.questsystem.AvertoxQuestSystemPlugin
api-version: "1.20"
softdepend: [Vault]
commands:
  quest:
    description: Main quest system command
    usage: /quest
  event:
    description: Main event system command
    usage: /event
permissions:
  avertoxquest.admin:
    description: Access to admin quest and event commands
    default: op
